# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-17 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdata',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
    ]
