# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-17 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_orderdata_disabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='end',
            field=models.DateTimeField(verbose_name='截止时间'),
        ),
    ]
