# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-18 14:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20170817_2149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdata',
            old_name='data_id',
            new_name='sequence',
        ),
        migrations.AlterUniqueTogether(
            name='orderdata',
            unique_together=set([('order', 'sequence')]),
        ),
    ]
