# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-20 01:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_auto_20170818_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='截止时间'),
        ),
    ]
